---
- name: Execute 'ls /etc' and display the output
  hosts: all
  tasks:
    - name: Run ls command on /etc
      command: ls /etc
      register: ls_output

    - name: Display the output of the ls command
      debug:
        msg: "{{ ls_output.stdout }}"
